### ISSUE TITLE
Create SQLIte database

### ISSUE THREAD

**Issue by Demarsch** [Demarsch/gun-violence-dashboard#9]
Create an SQLIte database file and add the following tables to it:
1. Incidents
  - id: integer, identity, primary key // It has nothing to do with the Id of the incident from Kaggle (we won't store it)
  - date: date,
  - state: varchar(2) //Keep the abbreviation
  - city_or_county: varchar(100),
  - n_killed: number,
  - n_injured: number,
  - latitude: number(7, 4),
  - longitude: number(7, 4);
2. Participants
  - id: integer, identity, primary key,
  - incident_id: integer, foreign key for Incidents.id column
 - age: varchar(10), 
 - gender: varchar(10), 
 - type: varchar(20), 
 - status: varchar(20) 
3. Categories
  - id: integer, identity, primary key,
  - name: varchar(100)
4. IncidentCategories
  - incident_id: integer, foreign key for Incidents.id column,
  - category_id: integer, foreign key for Category.id column
5. Statistics
  - id: integer, identity, primary key
  - name: varchar(500),
  - source: varchar(500)
6. StatisticsData
  - id: integer, identity, primary key
  - statistics_id: integer, foreign key for Statistics.id column
  - state: varchar(2) //State abbreviation
  - value: number(18, 6) //For now lets assume that all stats will be numbers (optionally, with fractional part)

**Comment by n8dagrt** [comment]
Pushed
